export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'

export const CHANGE_HOT_RECOMMEND_LISTS = 'CHANGE_HOT_RECOMMEND_LISTS'

export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM'

export const CHANGE_NEW_TOP_LIST = 'CHANGE_NEW_TOP_LIST'
export const CHANGE_UP_TOP_LIST = 'CHANGE_UP_TOP_LIST'
export const CHANGE_ORIGIN_TOP_LIST = 'CHANGE_ORIGIN_TOP_LIST'
